import { eq, and, sql } from 'drizzle-orm'
import { db } from '@/lib/db'
import { tenants, annualRateConfig, invoices } from '@/lib/db/schema'

export interface DepositInterestResult {
  pdfBytes: Uint8Array
  tenantId: number
  tenantName: string
  depositAmount: number
  interestRate: number
  interestOwed: number
  year: number
  invoicePayload: {
    direction: string
    vendorId: number | null
    fundId: number | null
    amount: string
    invoiceDate: string
    dueDate: string
    paymentStatus: 'PENDING'
    createdBy: string
  }
}

const MA_STATUTORY_RATE = 0.03 // 3% per M.G.L. c. 186 §15B

/**
 * Generate security deposit interest record for a tenant.
 * Also prepares the AP invoice payload for insertion on delivery.
 */
export async function generateDepositInterest(
  tenantId: number,
  createdBy: string,
  fundId?: number | null
): Promise<DepositInterestResult> {
  const year = new Date().getFullYear()

  const [tenant] = await db
    .select()
    .from(tenants)
    .where(eq(tenants.id, tenantId))

  if (!tenant) throw new Error(`Tenant ${tenantId} not found`)

  const depositAmount = parseFloat(tenant.securityDepositAmount ?? '0')
  if (depositAmount <= 0) throw new Error(`Tenant ${tenantId} has no security deposit`)

  // Look up configured rate, fall back to statutory 3%
  const rateConfig = await db
    .select({ value: annualRateConfig.value })
    .from(annualRateConfig)
    .where(
      and(
        eq(annualRateConfig.fiscalYear, year),
        eq(annualRateConfig.configKey, 'security_deposit_interest_rate')
      )
    )
    .limit(1)

  const interestRate = rateConfig.length > 0
    ? parseFloat(rateConfig[0].value)
    : MA_STATUTORY_RATE

  const interestOwed = Math.round(depositAmount * interestRate * 100) / 100

  const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib')
  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold)

  const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n)

  let y = 740

  page.drawText(`Security Deposit Interest Record — ${year}`, {
    x: 50, y, size: 14, font: boldFont,
  })
  y -= 30

  page.drawText('Tenant Information', { x: 50, y, size: 10, font: boldFont })
  y -= 15
  page.drawText(`Name: ${tenant.name}`, { x: 50, y, size: 9, font })
  y -= 12
  page.drawText(`Unit: ${tenant.unitNumber}`, { x: 50, y, size: 9, font })
  y -= 12
  if (tenant.tenancyAnniversary) {
    page.drawText(`Tenancy Anniversary: ${tenant.tenancyAnniversary}`, { x: 50, y, size: 9, font })
    y -= 12
  }
  y -= 15

  page.drawText('Interest Calculation', { x: 50, y, size: 10, font: boldFont })
  y -= 15

  const calcLines: [string, string][] = [
    ['Security deposit amount', `$${fmt(depositAmount)}`],
    [`MA statutory interest rate (${(interestRate * 100).toFixed(2)}%)`, `× ${(interestRate * 100).toFixed(2)}%`],
    ['Interest owed', `$${fmt(interestOwed)}`],
  ]
  for (const [label, value] of calcLines) {
    page.drawText(label, { x: 50, y, size: 9, font })
    page.drawText(value, { x: 380, y, size: 9, font })
    y -= 16
  }

  y -= 20
  page.drawText('Legal Basis', { x: 50, y, size: 10, font: boldFont })
  y -= 15
  page.drawText('M.G.L. c. 186 §15B requires landlords to pay annual interest on', {
    x: 50, y, size: 9, font,
  })
  y -= 12
  page.drawText('security deposits at the rate set by the Commonwealth of Massachusetts.', {
    x: 50, y, size: 9, font,
  })
  y -= 12
  page.drawText('An AP payable has been created for this amount.', {
    x: 50, y, size: 9, font, color: rgb(0, 0.4, 0),
  })

  page.drawText('Generated by Renewal Initiatives Financial System', {
    x: 50, y: 30, size: 7, font, color: rgb(0.5, 0.5, 0.5),
  })

  const pdfBytes = await doc.save()
  const today = new Date().toISOString().substring(0, 10)

  return {
    pdfBytes,
    tenantId,
    tenantName: tenant.name,
    depositAmount,
    interestRate,
    interestOwed,
    year,
    invoicePayload: {
      direction: 'AP',
      // TODO (Phase 4): tenants need corresponding vendor records for AP aging to work correctly.
      // Each tenant should have a vendors row so the AP payable links properly.
      // For now this is null — the invoice will be created but won't appear in vendor AP aging.
      // See: compliance-workflow-engine-PHASES.md Phase 4 admin work.
      vendorId: null,
      fundId: fundId ?? null,
      amount: String(interestOwed),
      invoiceDate: today,
      dueDate: today,
      paymentStatus: 'PENDING',
      createdBy,
    },
  }
}
