import type { Vendor1099Row } from '@/lib/compliance/vendor-1099'

export interface Form1099Input {
  vendor: Vendor1099Row
  payer: {
    tin: string
    name: string
    address: string
    city: string
    state: string
    zip: string
  }
  year: number
}

/**
 * Generate a 1099-NEC summary PDF for one vendor using pdf-lib.
 */
export async function generate1099PDF(input: Form1099Input): Promise<Uint8Array> {
  const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib')

  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold)

  const { vendor, payer, year } = input
  const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n)

  let y = 740

  // Title
  page.drawText(`1099-NEC — Nonemployee Compensation — ${year}`, {
    x: 50,
    y,
    size: 14,
    font: boldFont,
  })
  y -= 30

  // Payer info
  page.drawText('PAYER Information', { x: 50, y, size: 10, font: boldFont })
  y -= 15
  page.drawText(`TIN: ${payer.tin}`, { x: 50, y, size: 9, font })
  y -= 12
  page.drawText(payer.name, { x: 50, y, size: 9, font })
  y -= 12
  page.drawText(`${payer.address}, ${payer.city}, ${payer.state} ${payer.zip}`, {
    x: 50,
    y,
    size: 9,
    font,
  })
  y -= 25

  // Recipient info
  page.drawText('RECIPIENT Information', { x: 50, y, size: 10, font: boldFont })
  y -= 15
  page.drawText(`Name: ${vendor.vendorName}`, { x: 50, y, size: 9, font })
  y -= 12
  if (vendor.address) {
    page.drawText(`Address: ${vendor.address}`, { x: 50, y, size: 9, font })
    y -= 12
  }
  if (vendor.taxId) {
    page.drawText(`TIN: ${vendor.taxId}`, { x: 50, y, size: 9, font })
    y -= 12
  }
  y -= 15

  // Box 1
  page.drawText('Box 1 — Nonemployee Compensation', { x: 50, y, size: 10, font: boldFont })
  y -= 20
  page.drawText(`$${fmt(vendor.totalPaid)}`, { x: 50, y, size: 16, font: boldFont })
  y -= 30

  // W-9 Status
  page.drawText(`W-9 Status: ${vendor.w9Status}`, { x: 50, y, size: 9, font })
  if (vendor.w9CollectedDate) {
    y -= 12
    page.drawText(`W-9 Collected: ${vendor.w9CollectedDate}`, { x: 50, y, size: 9, font })
  }

  // Footer
  page.drawText('Generated by Renewal Initiatives Financial System', {
    x: 50,
    y: 30,
    size: 7,
    font,
    color: rgb(0.5, 0.5, 0.5),
  })

  return doc.save()
}
