import type { W2Row } from '@/lib/reports/w2-verification'

/**
 * W-2 PDF Generator
 *
 * Uses pdf-lib to fill IRS W-2 form fields.
 * Since we don't have the actual IRS PDF template bundled,
 * we generate a structured W-2 summary PDF using pdf-lib.
 */

export interface W2GeneratorInput {
  employee: W2Row
  employer: {
    ein: string
    name: string
    address: string
    city: string
    state: string
    zip: string
  }
  year: number
}

/**
 * Generate a W-2 summary PDF for one employee using pdf-lib.
 */
export async function generateW2PDF(input: W2GeneratorInput): Promise<Uint8Array> {
  const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib')

  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792]) // Letter size
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold)

  const { employee, employer, year } = input
  const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n)

  let y = 740

  // Title
  page.drawText(`W-2 Wage and Tax Statement — ${year}`, {
    x: 50,
    y,
    size: 14,
    font: boldFont,
  })
  y -= 30

  // Employer info
  page.drawText('Employer Information', { x: 50, y, size: 10, font: boldFont })
  y -= 15
  page.drawText(`EIN: ${employer.ein}`, { x: 50, y, size: 9, font })
  y -= 12
  page.drawText(employer.name, { x: 50, y, size: 9, font })
  y -= 12
  page.drawText(`${employer.address}, ${employer.city}, ${employer.state} ${employer.zip}`, {
    x: 50,
    y,
    size: 9,
    font,
  })
  y -= 25

  // Employee info
  page.drawText('Employee Information', { x: 50, y, size: 10, font: boldFont })
  y -= 15
  page.drawText(`Name: ${employee.employeeName}`, { x: 50, y, size: 9, font })
  y -= 12
  page.drawText(`ID: ${employee.employeeId}`, { x: 50, y, size: 9, font })
  y -= 25

  // W-2 Boxes
  page.drawText('W-2 Box Values', { x: 50, y, size: 10, font: boldFont })
  y -= 20

  const boxes: [string, number][] = [
    ['Box 1 — Wages, tips, other compensation', employee.box1],
    ['Box 2 — Federal income tax withheld', employee.box2],
    ['Box 3 — Social Security wages', employee.box3],
    ['Box 4 — Social Security tax withheld', employee.box4],
    ['Box 5 — Medicare wages and tips', employee.box5],
    ['Box 6 — Medicare tax withheld', employee.box6],
    ['Box 16 — State wages, tips, etc.', employee.box16],
    ['Box 17 — State income tax', employee.box17],
  ]

  for (const [label, value] of boxes) {
    page.drawText(label, { x: 50, y, size: 9, font })
    page.drawText(`$${fmt(value)}`, { x: 400, y, size: 9, font, color: rgb(0, 0, 0) })
    y -= 16
  }

  if (employee.hasWageBaseExceeded) {
    y -= 10
    page.drawText('* Social Security wage base cap applied to Box 3', {
      x: 50,
      y,
      size: 8,
      font,
      color: rgb(0.6, 0, 0),
    })
  }

  // Footer
  page.drawText('Generated by Renewal Initiatives Financial System', {
    x: 50,
    y: 30,
    size: 7,
    font,
    color: rgb(0.5, 0.5, 0.5),
  })

  return doc.save()
}

/**
 * Generate a combined W-2 PDF for all employees.
 */
export async function generateCombinedW2PDF(
  employees: W2Row[],
  employer: W2GeneratorInput['employer'],
  year: number
): Promise<Uint8Array> {
  const { PDFDocument } = await import('pdf-lib')
  const combined = await PDFDocument.create()

  for (const emp of employees) {
    const singlePdf = await generateW2PDF({ employee: emp, employer, year })
    const tempDoc = await PDFDocument.load(singlePdf)
    const pages = await combined.copyPages(tempDoc, tempDoc.getPageIndices())
    for (const page of pages) {
      combined.addPage(page)
    }
  }

  return combined.save()
}
