import type { funds } from '@/lib/db/schema'

type SeedFund = typeof funds.$inferInsert

export const seedFunds: SeedFund[] = [
  // AHP loan proceeds are unrestricted per board resolution (2026-02).
  // No separate AHP fund needed — loan liability tracked via account 2500.
  { name: 'General Fund', restrictionType: 'UNRESTRICTED', isSystemLocked: true, description: 'Default unrestricted operating fund' },
  {
    name: 'CPA Fund',
    restrictionType: 'RESTRICTED',
    fundingCategory: 'GRANT',
    isSystemLocked: false,
    description: 'Community Preservation Act funds',
    amount: '250000.00',
    type: 'UNCONDITIONAL',
    startDate: '2025-07-01',
    endDate: '2026-06-30',
    status: 'ACTIVE',
    reportingFrequency: 'ANNUAL',
    revenueClassification: 'GRANT_REVENUE',
  },
  {
    name: 'MassDev Fund',
    restrictionType: 'RESTRICTED',
    fundingCategory: 'GRANT',
    isSystemLocked: false,
    description: 'MassDevelopment grant funds',
    amount: '150000.00',
    type: 'CONDITIONAL',
    conditions: 'Job creation targets and quarterly reporting',
    startDate: '2025-03-01',
    endDate: '2026-08-31',
    status: 'ACTIVE',
    matchRequirementPercent: '25.00',
    reportingFrequency: 'QUARTERLY',
    revenueClassification: 'GRANT_REVENUE',
  },
  {
    name: 'HTC Equity Fund',
    restrictionType: 'RESTRICTED',
    fundingCategory: 'GRANT',
    isSystemLocked: false,
    description: 'Historic Tax Credit equity funds',
    amount: '800000.00',
    type: 'CONDITIONAL',
    conditions: 'NPS Part 3 certification and 5-year recapture period compliance',
    startDate: '2024-06-01',
    endDate: '2029-06-01',
    status: 'ACTIVE',
    retainagePercent: '10.00',
    reportingFrequency: 'ANNUAL',
    revenueClassification: 'GRANT_REVENUE',
  },
  {
    name: 'MassSave Fund',
    restrictionType: 'RESTRICTED',
    fundingCategory: 'GRANT',
    isSystemLocked: false,
    description: 'MassSave energy rebate funds',
    amount: '45000.00',
    type: 'UNCONDITIONAL',
    startDate: '2025-09-01',
    endDate: '2026-03-31',
    status: 'ACTIVE',
    revenueClassification: 'GRANT_REVENUE',
  },
]
