import type { funds } from '@/lib/db/schema'

type SeedFund = typeof funds.$inferInsert

export const seedFunds: SeedFund[] = [
  { name: 'General Fund', restrictionType: 'UNRESTRICTED', isSystemLocked: true, description: 'Default unrestricted operating fund' },
  {
    name: 'AHP Fund',
    restrictionType: 'RESTRICTED',
    isSystemLocked: false,
    description: 'Affordable Housing Program grant funds',
    amount: '500000.00',
    type: 'CONDITIONAL',
    conditions: 'Complete renovation milestones per AHP agreement',
    startDate: '2025-01-01',
    endDate: '2027-12-31',
    status: 'ACTIVE',
    reportingFrequency: 'QUARTERLY',
  },
  {
    name: 'CPA Fund',
    restrictionType: 'RESTRICTED',
    isSystemLocked: false,
    description: 'Community Preservation Act funds',
    amount: '250000.00',
    type: 'UNCONDITIONAL',
    startDate: '2025-07-01',
    endDate: '2026-06-30',
    status: 'ACTIVE',
    reportingFrequency: 'ANNUAL',
  },
  {
    name: 'MassDev Fund',
    restrictionType: 'RESTRICTED',
    isSystemLocked: false,
    description: 'MassDevelopment grant funds',
    amount: '150000.00',
    type: 'CONDITIONAL',
    conditions: 'Job creation targets and quarterly reporting',
    startDate: '2025-03-01',
    endDate: '2026-08-31',
    status: 'ACTIVE',
    matchRequirementPercent: '25.00',
    reportingFrequency: 'QUARTERLY',
  },
  {
    name: 'HTC Equity Fund',
    restrictionType: 'RESTRICTED',
    isSystemLocked: false,
    description: 'Historic Tax Credit equity funds',
    amount: '800000.00',
    type: 'CONDITIONAL',
    conditions: 'NPS Part 3 certification and 5-year recapture period compliance',
    startDate: '2024-06-01',
    endDate: '2029-06-01',
    status: 'ACTIVE',
    retainagePercent: '10.00',
    reportingFrequency: 'ANNUAL',
  },
  {
    name: 'MassSave Fund',
    restrictionType: 'RESTRICTED',
    isSystemLocked: false,
    description: 'MassSave energy rebate funds',
    amount: '45000.00',
    type: 'UNCONDITIONAL',
    startDate: '2025-09-01',
    endDate: '2026-03-31',
    status: 'ACTIVE',
  },
]
